### ISSUE TITLE
Reproducing your experimental results

### ISSUE THREAD

**Issue by jyhong0304** [MhmdSaiid/TypeEmbedding#1]
Hi,

First of all, your paper was very interesting and I would like to thank you for deciding to share your code.
I tried to reproduce your experiments on my own but I couldn't get the expected results.
So when will you post your full code?

Regards,
Jinyung Hong

**Comment by mojsaeed** [comment]
Hi!
I am glad you find the paper interesting.
I am currently working on it and hopefully should be done by next week. I will ping you once up.

**Comment by mojsaeed** [comment]
Hi again,
The code to generate the Type Embeddings and run the (intrinsic) experiments is up. The rest are there, and I will be testing within next week due to some GPU constraints. I will close this issue, but feel free to open a new one in case you have some troubles with the code.

Regards,
Mohammed SAEED
